import turtle



#1 pixel = 20

screen = turtle.Screen()
screen.bgcolor("white")

#set position

bob = turtle.Turtle()
bob.speed(100)
bob.left(90)
bob.color('white')
bob.penup()
bob.forward(200)
bob.left(90)
bob.forward(100)


#start drawing(hat)
bob.fillcolor("red")
bob.begin_fill()
bob.right(180)
bob.pendown()
bob.forward(120)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(80)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(220)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.end_fill()
bob.right(180)


#head
bob.color('#ffd987')#color skin
bob.begin_fill()
bob.penup()
bob.forward(40)
bob.right(90)
bob.pendown()
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(60)
bob.left(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(160)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.color('#ffd987')
bob.forward(140)
bob.end_fill()
bob.forward(20)
bob.color('white')

#Details of head
bob.color('brown')
bob.begin_fill()
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(40)
bob.left(90)
bob.forward(40)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(60)
bob.end_fill()
bob.color('brown')
bob.begin_fill()
bob.penup()

bob.left(90)
bob.forward(20)
bob.right(90)
bob.pendown()

bob.forward(20)
bob.left(90)
bob.forward(60)
bob.left(90)
bob.forward(40)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(40)
bob.left(90)
bob.end_fill()
bob.penup()
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(120)

#eyes
bob.pendown()
bob.color('black')
bob.begin_fill()
bob.right(90)
bob.forward(40)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.left(90)
bob.forward(20)
bob.end_fill()
#mouth
bob.color('black')
bob.begin_fill()
bob.penup()
bob.left(90)
bob.forward(40)
bob.left(90)
bob.pendown()
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(80)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.end_fill()

#cloths(redpart)
bob.color('red')
bob.begin_fill()
bob.penup()
bob.right(180)
bob.forward(60)
bob.pendown()
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(40)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(60)
bob.right(90)
bob.forward(20)
bob.end_fill()


#arm(rightarm)
bob.color('#ffd987')#color skin
bob.begin_fill()
bob.penup()
bob.right(90)
bob.forward(80)
bob.pendown()
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.left(90)
bob.forward(60)
bob.left(90)
bob.forward(40)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.end_fill()
#shirt(cooking)
bob.color('blue')#color skin
bob.begin_fill()
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(60)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(60)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(60)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(40)
bob.left(90)
bob.forward(40)
bob.left(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(60)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.end_fill()

#leftarm(red)
bob.color('red')
bob.begin_fill()
bob.penup()
bob.right(90)
bob.forward(120)
bob.pendown()
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(60)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.end_fill()


#leftarmhand
bob.color('#ffd987')#color skin
bob.begin_fill()
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(60)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.end_fill()

          
#shoes(left)
bob.color('brown')#color skin
bob.begin_fill()
bob.penup()
bob.left(90)
bob.forward(60)
bob.right(90)
bob.pendown()
bob.right(180)
bob.forward(60)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(80)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.end_fill()

#rightshoes
bob.color('brown')#color skin
bob.begin_fill()
bob.right(90)
bob.penup()
bob.forward(140)
bob.pendown()
bob.forward(60)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(80)
bob.right(90)
bob.forward(40)
bob.end_fill()
#shirt details
bob.color('yellow')#color skin
bob.begin_fill()
bob.penup()
bob.forward(80)
bob.pendown()
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.end_fill()

bob.color('yellow')#color skin
bob.begin_fill()
bob.penup()
bob.left(90)
bob.forward(60)
bob.pendown()
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.end_fill()

bob.color('red')#color skin
bob.begin_fill()
bob.penup()
bob.forward(20)
bob.pendown()
bob.forward(40)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(40)
bob.end_fill()
bob.hideturtle()
turtle.done()